### ISSUE TITLE
XP as depth display should display exact depth as level

### ISSUE THREAD

**Issue by JandBDavenport** [showierdata9978/Pickaxe-mod#11]
Currently having depth show on the xp bar makes it very difficult to go to an exact depth for certain things such as mining the arkenstone. Having the xp bar show the current depth as the player level could solve this issue.

**Comment by showierdata9978** [comment]
The reason i did not add that is because of the chords i added (the y is exactly the same)

**Comment by showierdata9978** [comment]
Bro really reset my bedrock progress
