### ISSUE TITLE
XP Bar - Chest Timer

### ISSUE THREAD

**Issue by MystWraith** [showierdata9978/Pickaxe-mod#13]
**Is your feature request related to a problem? Please describe.**
It could be handy to know when the cooldown for a chest has completed, that way I'm not mining something stupid like dirt.

**Describe the solution you'd like**
I'd like it to have an option to either do `Chest Timer Fill` or `Chest Timer Deplete`
Either one will change the XP bar according to the timer for Chests.
Fill starts at Zero and "fills" as the timer ticks down.
Deplete is the exact opposite.
Alternate names could be `Chest Timer (Low to High)` and `Chest Timer (High to Low)`

**Describe alternatives you've considered**
Obviously I could just set a timer for 1000s, but this feels clunky to me personally.

**Additional context**
I could understand how this could be seen as overpowered, as it allows you to select where you want your chest to appear, or switch gear accordingly. Ergo, I would not be offended if this is shot down.

**Comment by showierdata9978** [comment]
RotemRotem wants to implement this; I told him to ask sputt if that was
allowed

**Comment by MystWraith** [comment]
Nice! I look forward to some news!
