### ISSUE TITLE
XP Bar - Forge Timer

### ISSUE THREAD

**Issue by MystWraith** [showierdata9978/Pickaxe-mod#14]
**Is your feature request related to a problem? Please describe.**
I think this item is similar to the money instead of hunger bar feature. It can be annoying to have to press tab to check on forge progress, especially on long forge times.

**Describe the solution you'd like**
I think it could be interesting to have a red XP bar during forging that drains as it completes, and a green full one when the forge is complete, and an empty green one when it is ready.

**Describe alternatives you've considered**
You can literally just press tab.

**Additional context**
This is definitely a QOL improvement, and does not have any particular merit. Additionally, I am aware that the way that I described could be quite difficult, and I apologize for such.

**Comment by showierdata9978** [comment]
Dupe
