### ISSUE TITLE
[bug] Hunger bar looks odd

### ISSUE THREAD

**Issue by MystWraith** [showierdata9978/Pickaxe-mod#15]
**Describe the bug**
The final hunger bar is still shown with the money, but the border is removed.

**To Reproduce**
1. Join in a way that enables the mod
2. Look at the hunger bar

**Expected behavior**
The hunger bar is either completely hidden or the border is included on the final hunger icon.

**Screenshots**
![Your own screenshot of the error on the main page.](https://camo.githubusercontent.com/74efad75d9fbc0488309a5936a25e0ae08be0394943f881b3be3e5cbfaa3efd9/68747470733a2f2f63646e2e6d6f6472696e74682e636f6d2f646174612f76374e41364f49742f696d616765732f633538363538623365623565303163353564656166306332373333353633356334336466346431632e706e67)

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
I could understand the point of leaving the final hunger icon around to show if hunger is applied, though it's purpose alluded me for a while. Though, if there could be an option to completely hide it, I would appreciate it. Also, if it is going to stay, please add the background back please.

**Comment by JandBDavenport** [comment]
ShowierData is aware of this but doesnt know how to fix it

**Comment by MystWraith** [comment]
I think it has to do with the background of the hunger bar being a separate render. It actually renders the entire empty bar all at once (if I recall correctly) and it might help if the sprite for the background hunger bar is not removed but changed to a different version containing only the last one.

**Comment by MystWraith** [comment]
Bc it seems like the texture for full hunger was removed and so was the background texture, causing the weird visual bug.

**Comment by MystWraith** [comment]
I checked the source and noticed that hunger is actually getting shrunk to width 0, which is interesting. I don't know if this method could fix this bug, but it might be possible to change textures.
