### ISSUE TITLE
Quick Forge Fill

### ISSUE THREAD

**Issue by MystWraith** [showierdata9978/Pickaxe-mod#29]
**Is your feature request related to a problem? Please describe.**
It's annoying to have to click in 5 items for a forge (especially since some items look the same and cannot be merged).

**Describe the solution you'd like**
When you click in an item into the forge, it will find all duplicates in your inventory and put in 4.

**Describe alternatives you've considered**
Juz do it by hand.

**Additional context**
I can work on this one. It will be a cool learning experience, but if @showierdata9978  want's it, by all means, take it.

**Comment by showierdata9978** [comment]
I need to ask sputt about this

**Comment by MystWraith** [comment]
👍

**Comment by sporefreak** [comment]
There is a texture pack that will change items that share textures (iron ingots, celestial ingots, steel ingots for example)
This is a good alternative to using mods that would be considered abusable for some reason or another.

**Comment by MystWraith** [comment]
Yeah, but even for things like rockite where I might have an inventory full, the texture pack won't change it. It just gets really annoying.

**Comment by showierdata9978** [comment]
DF Rules
