### ISSUE TITLE
Game crashes while trying to read pickaxe mod's config

### ISSUE THREAD

**Issue by TrueDiegoWasAlsoTaken** [showierdata9978/Pickaxe-mod#57]
The game loads perfectly as long as you keep the default config. As soon as you change anything on pickaxe mod's configs (config file is created) the game will crash trying to read said config on subsequent launches.

**1.** Launch game, loads perfectly fine
**1a.** Relaunch game, still loads perfectly fine
**2.** Change pickaxe mod config with mod menu, config file is created after saving
**3.** Relaunch game after changing config

**Expected:** Game loads perfectly fine with the configs you set
**What actually happens:** Crash trying to read config

**Minecraft version:**
Minecraft 1.20.4
Fabric Loader 0.15.7

**Mods used:**
Fabric API 0.96.4+1.20.4
Mod Menu 9.0.0
Pickaxe 1.4.5
YetAnotherConfigLib 3.3.2+1.20.4

**Comment by showierdata9978** [comment]
This ain't really maintained anymore, I'm surprised it works on 1.20.4

**Comment by TruestClover** [comment]
Here to confirm the crash still happens with Pickaxe 1.4.6, tested with the same mods on the initial report.

**Comment by showierdata9978** [comment]
whats in   `.minecraft/config/pickaxe.properties.json`?

**Comment by TruestClover** [comment]
`{"enabled":true,"XPBarType":"Radiation","AutoCL":false,"ShowLockIcon":true,"itemconfig":{"x":0,"y":0,"overclocker_color":-65536,"sage_color":-3407668,"sanded_color":-2505116},"cctconfig":{"enabled":false,"soundEnabled":false,"enabledOutsidePickaxe":false,"location":"TOPRIGHT"},"hideNonPickaxePlayers":true,"pois":["SPAWN","MUSEUM","MEDALS","SPAWN_SHOP","BACKPACK_SHOP","ELEVATOR_SHOP","Luigi","NETHER_HUB","MESA_SHACK","TECH_CRAFTING","TRADER","ENCHANT_PROSP","ENCHANT_EFF","ENCHANT_LUCK","ENCHANT_FESTIVE","ENCHANT_AUTOFORGE","ENCHANT_PLATED","BAZZAR","DIRT_GOD","SAND_GOD"],"enable_poi":false,"hide_plot_ads":true,"msgStackConfig":{"enabled":false,"text":"\u00268[\u0026bx{num}\u00268]"},"mdtConfig":{"location":"TOPRIGHT","soundEnabled":false,"reverseCCTOrder":true,"enabled":true},"chatClear":{}}`
(kinda wild its all on a single line)

**Comment by showierdata9978** [comment]
I don't know

**Comment by sandstripes** [comment]
this seems to be caused by the `chatClear` property in the config. if you remove the `,"chatClear":{}` from the `pickaxe.properties.json` it works for some reason
i brute forced it and it was the last possible thing
