### ISSUE TITLE
Hide non-pickaxe players in the player tab list while on the pickaxe plot

### ISSUE THREAD

**Issue by JandBDavenport** [showierdata9978/Pickaxe-mod#6]
fairly self-explanatory, just make only pickaxe players show in the tab list (maybe always include Sputt and Acod_ so you can still see them while they are in /dev or /build)

**Comment by showierdata9978** [comment]
Working on this now

**Comment by showierdata9978** [comment]
![image](https://github.com/showierdata9978/Pickaxe-mod/assets/68120127/61936973-1b4a-4f4b-8eed-7987cf32f7c1)

**Comment by showierdata9978** [comment]
https://github.com/showierdata9978/Pickaxe-mod/commit/615aa6e5b783c4e45b3db28b4fab0c14167053b5
