### ISSUE TITLE
Bossbars are still displaced by hidden bossbars

### ISSUE THREAD

**Issue by JandBDavenport** [showierdata9978/Pickaxe-mod#7]
When setting XP bar to display depth (and maybe radiation too), the other bossbars on screen are still displaced by the amount that the bar would cause if visible.

1. Enable XP bar displaying depth
2. Gain a depth of at least 1
3. break a block, lose o2, gain radiation
4. See that bossbar is lower then expected

It is expected that the other bossbars besides the hidden one would act as though the hidden one does not exist, and attempt to stay at the top of the screen.

![image](https://github.com/showierdata9978/Pickaxe-mod/assets/112143869/89a12e6e-f228-4ac5-b5ec-bfd22623c43e)
Bossbars before entering a mine

![image](https://github.com/showierdata9978/Pickaxe-mod/assets/112143869/346aafe8-f1eb-46d3-996a-3af71b84d8fe)
Bossbars after entering a mine, notice the displacement

**Comment by showierdata9978** [comment]
i have no idea how to fix this; so i asked
https://discord.com/channels/507304429255393322/807617700734042122/1140504635895984258 (Fabric discord server)

**Comment by showierdata9978** [comment]
bro really reset my bedrock progress

**Comment by MystWraith** [comment]
I don't know if this was already fixed, but it can be solved with another mixin function. In the `BossBarHud` class, around `L15` or `LINENUMBER 50` there is a variable labled `j` in the standard code and it describes the height where the bossbar is to be shown. This variable is incremented per every bossbar. When cancelling the rendering of the bossbar, decrement this value or cancel the increment action.

I recommend an `@Inject` right before the `IF_IMPLICIT` at `L16`

I could work on a pull request if it's desired.

**Comment by MystWraith** [comment]
Just confirmed that it is still around, and if it's ok with showier, I can create a pull request to fix it

**Comment by showierdata9978** [comment]
yeah i saw that if you had read the thing in #8 i had to get help

i just have not gotten around to implementing it
